/*
 * Port_PBcfg.c
 *
 *  Created on: Apr 22, 2019
 *      Author: r
 */

#include "myPort.h"


Port_ConfigType Port_Configuration = {

		PORT_A,	PIN_0,	PORT_PIN_IN,	PULL_DOWN,
		PORT_A,	PIN_1,	PORT_PIN_IN,	PULL_DOWN,
		PORT_A,	PIN_2,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_A,	PIN_3,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_A,	PIN_4,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_A,	PIN_5,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_A,	PIN_6,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_A,	PIN_7,	PORT_PIN_IN, 	PULL_DOWN,

		PORT_B,	PIN_0,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_B,	PIN_1,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_B,	PIN_2,	PORT_PIN_IN,	PULL_DOWN,
		PORT_B,	PIN_3,	PORT_PIN_IN,	PULL_DOWN,
		PORT_B,	PIN_4,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_B,	PIN_5,	PORT_PIN_IN,	PULL_DOWN,
		PORT_B,	PIN_6,	PORT_PIN_IN,	PULL_DOWN,
		PORT_B,	PIN_7,	PORT_PIN_IN,	PULL_DOWN,

		PORT_C,	PIN_0,	PORT_PIN_IN,	PULL_DOWN,
		PORT_C,	PIN_1,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_C,	PIN_2,	PORT_PIN_IN,	PULL_DOWN,
		PORT_C,	PIN_3,	PORT_PIN_IN,	PULL_DOWN,
		PORT_C,	PIN_4,	PORT_PIN_IN, 	PULL_DOWN,
		PORT_C,	PIN_5,	PORT_PIN_IN,	PULL_DOWN,
		PORT_C,	PIN_6,	PORT_PIN_IN,	PULL_DOWN,
		PORT_C,	PIN_7,	PORT_PIN_IN,	PULL_DOWN,

		PORT_D,	PIN_0,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_1,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_2,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_3,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_4,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_5,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_6,	PORT_PIN_IN,	PULL_DOWN,
		PORT_D,	PIN_7,	PORT_PIN_IN,	PULL_DOWN,



};




